import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Container from '@mui/material/Container';

export default function Home() {
  return (
    <Container maxWidth='false' sx={{ padding: 0 }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      Welcome blurb
      {/* TODO: welcome blurb */}

      Blogs
      {/* TODO: blogs */}
    </Container>
  )
}