# References:
#   syntax   │ https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#   basics   │ https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#create-an-example-workflow
#   env vars │ https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

name: lint_validation
run-name: ${{github.actor}} running lint_validation

#───────────────────────────┐
#  Triggers                 │
#───────────────────────────┘
on:
  push:
    branches: [main]
    # paths: [./**]
  pull_request:
    branches: [main]
    # paths: [./**]

#───────────────────────────┐
#  Config                   │
#───────────────────────────┘
defaults:
  run:
    shell: bash
    working-directory: ./

#───────────────────────────┐
#  Actions                  │
#───────────────────────────┘
jobs:
  lint_validation:
    name: Lint Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Fetch Deps
        id: fetch-deps
        run: |
          pip install -r ./requirements.txt

      - name: Lint Python Format
        id: lint-python-format
        run: |
          black ./ --check

      - name: Lint Python Docstrings
        id: lint-python-docstrings
        run: |
          interrogate ./ -vv --fail-under=100

      ## TODO: can't get this to work with the plugin
      # - name: Lint JS/TS
      #   id: lint-js-ts
      #   uses: creyD/prettier_action@v4.3
      #   with:
      #     prettier_options: ""
      #     prettier_plugins: "prettier-plugin-tailwindcss"

    ## TODO: a job that tries to build the application
